//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CES.CoreApi.Payout.Service.Business.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CES.CoreApi.Payout.Service.Business.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Payout Call Failed: .
        /// </summary>
        public static string ConfirmPayoutFailed {
            get {
                return ResourceManager.GetString("ConfirmPayoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Provider Instance..
        /// </summary>
        public static string CouldNotCreateProviderInstance {
            get {
                return ResourceManager.GetString("CouldNotCreateProviderInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Country Code must be 2 characters long..
        /// </summary>
        public static string ErrorCountryCodeLength2 {
            get {
                return ResourceManager.GetString("ErrorCountryCodeLength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Country Code must be 3 characters long..
        /// </summary>
        public static string ErrorCountryCodeLength3 {
            get {
                return ResourceManager.GetString("ErrorCountryCodeLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Country Code can only contain letters..
        /// </summary>
        public static string ErrorCountryCodeLetters {
            get {
                return ResourceManager.GetString("ErrorCountryCodeLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Access:.
        /// </summary>
        public static string ErrorDatabaseAccess {
            get {
                return ResourceManager.GetString("ErrorDatabaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Country Code..
        /// </summary>
        public static string ErrorInvalidCountryCode {
            get {
                return ResourceManager.GetString("ErrorInvalidCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money amount is not valid..
        /// </summary>
        public static string ErrorMoneyAmountInvalid {
            get {
                return ResourceManager.GetString("ErrorMoneyAmountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money has wrong # of decimal places.  Expected 2, but found: .
        /// </summary>
        public static string ErrorMoneyBadPrecision {
            get {
                return ResourceManager.GetString("ErrorMoneyBadPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Currency Code. .
        /// </summary>
        public static string ErrorMoneyCurrencyCode {
            get {
                return ResourceManager.GetString("ErrorMoneyCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must be exactly 3 characters long..
        /// </summary>
        public static string ErrorMoneyCurrencyLength {
            get {
                return ResourceManager.GetString("ErrorMoneyCurrencyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create Money value: .
        /// </summary>
        public static string ErrorMoneyFailedToCreate {
            get {
                return ResourceManager.GetString("ErrorMoneyFailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operations on Mis-Matched Currencies..
        /// </summary>
        public static string ErrorMoneyMismatchedCurrency {
            get {
                return ResourceManager.GetString("ErrorMoneyMismatchedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Amount must be a postive number..
        /// </summary>
        public static string ErrorMoneyNegativeAmount {
            get {
                return ResourceManager.GetString("ErrorMoneyNegativeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Currency cannot be NULL..
        /// </summary>
        public static string ErrorMoneyNullCurrency {
            get {
                return ResourceManager.GetString("ErrorMoneyNullCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not supplied..
        /// </summary>
        public static string FieldNotSupplied {
            get {
                return ResourceManager.GetString("FieldNotSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call: .
        /// </summary>
        public static string GC_Call {
            get {
                return ResourceManager.GetString("GC_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldenCrown did not return exactly 1 order for the PIN :.
        /// </summary>
        public static string GCNotExactlyOneOrderForPin {
            get {
                return ResourceManager.GetString("GCNotExactlyOneOrderForPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldenCrown Response is null. .
        /// </summary>
        public static string GCResponseNull {
            get {
                return ResourceManager.GetString("GCResponseNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC:.
        /// </summary>
        public static string GCServiceError {
            get {
                return ResourceManager.GetString("GCServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldenCrown did not return any orders for the PIN..
        /// </summary>
        public static string GCZeroOrdersForPIN {
            get {
                return ResourceManager.GetString("GCZeroOrdersForPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Transaction Info Call Failed..
        /// </summary>
        public static string GetTransactionInfoFailed {
            get {
                return ResourceManager.GetString("GetTransactionInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID Type.  .
        /// </summary>
        public static string InvalidIDType {
            get {
                return ResourceManager.GetString("InvalidIDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Order PIN..
        /// </summary>
        public static string InvalidOrderPIN {
            get {
                return ResourceManager.GetString("InvalidOrderPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request Message.  Missing required elements..
        /// </summary>
        public static string InvalidRequestMessage {
            get {
                return ResourceManager.GetString("InvalidRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Beneficiary Name.  .
        /// </summary>
        public static string MissingBeneficiaryName {
            get {
                return ResourceManager.GetString("MissingBeneficiaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction has no payout amount recorded..
        /// </summary>
        public static string MissingPayoutAmount {
            get {
                return ResourceManager.GetString("MissingPayoutAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Provider found for this transaction..
        /// </summary>
        public static string NoProviderFound {
            get {
                return ResourceManager.GetString("NoProviderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Provider Interface found..
        /// </summary>
        public static string NoProviderInterfaceFound {
            get {
                return ResourceManager.GetString("NoProviderInterfaceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not available for payout.
        /// </summary>
        public static string OrderNoAvailable {
            get {
                return ResourceManager.GetString("OrderNoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout Transaction Call Failed: .
        /// </summary>
        public static string PayoutTransactionFailed {
            get {
                return ResourceManager.GetString("PayoutTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Order PIN entered does not match any Partner Orders..
        /// </summary>
        public static string PINDidNotMatchPartner {
            get {
                return ResourceManager.GetString("PINDidNotMatchPartner", resourceCulture);
            }
        }
    }
}
